CREATE DATABASE chakray;

USE chakray;

CREATE TABLE TB_USER (
	ID int IDENTITY(1,1) NOT NULL,
	EMAIL varchar(120) COLLATE Modern_Spanish_CI_AS NOT NULL,
	NAME varchar(150) COLLATE Modern_Spanish_CI_AS NOT NULL,
	PASSWORD varchar(250) COLLATE Modern_Spanish_CI_AS NOT NULL,
	CREATED datetime NOT NULL,
	CONSTRAINT PK__TB_USER__3214EC275225D358 PRIMARY KEY (ID)
);

CREATE TABLE TB_ADDRESS (
	ID int IDENTITY(1,1) NOT NULL,
	NAME varchar(150) COLLATE Modern_Spanish_CI_AS NOT NULL,
	STREET varchar(120) COLLATE Modern_Spanish_CI_AS NOT NULL,
	COUNTRY_CODE varchar(250) COLLATE Modern_Spanish_CI_AS NOT NULL,
	USER_ID int NOT NULL,
	CONSTRAINT PK__TB_ADDRE__3214EC276E67EC85 PRIMARY KEY (ID)
);
